import Link from "next/link";
import { notFound } from "next/navigation";
import { requireAdmin } from "@/lib/auth";
import { createClient } from "@/lib/supabase/server";
import { PageHeader } from "@/components/PageHeader";
import { StatusBadge } from "@/components/StatusBadge";
import { EmptyState } from "@/components/EmptyState";
import { ClientEditForm } from "@/components/ClientEditForm";
import { ClientLifecycleActions } from "@/components/ClientLifecycleActions";
import { BillingActions } from "@/components/BillingActions";
import { ConnectionVerifyButton } from "@/components/ConnectionVerifyButton";
import { AutomationControl } from "@/components/AutomationControl";
import { formatDate, formatDateTime, formatMoney } from "@/lib/utils";
import { updatePortalConfig } from "@/lib/actions";

export const dynamic="force-dynamic";

export default async function ClientDetail({params}:{params:Promise<{id:string}>}){
 const{id}=await params;await requireAdmin();const s=await createClient();
 const [client,portal,subs,connections,workflows,reports,tickets,tasks,onboarding,events]=await Promise.all([
  s.from("clients").select("id,company_name,contact_name,email,phone,status,notes,created_at,updated_at").eq("id",id).maybeSingle(),
  s.from("client_portal_config").select("client_id,slug,portal_title,logo_url,favicon_url,primary_color,accent_color,enabled_modules,dashboard_config,kpi_config,terminology").eq("client_id",id).maybeSingle(),
  s.from("subscriptions").select("id,service_name,monthly_amount,currency,billing_day,auto_renew,status,start_date,current_period_start,current_period_end,cancelled_at").eq("client_id",id).order("created_at",{ascending:false}).limit(20),
  s.from("client_connections").select("id,n8n_instance_id,status,last_verified_at,last_error").eq("client_id",id).limit(20),
  s.from("workflows").select("id,workflow_name,business_name,business_job,status,actual_state,desired_state,client_visible,last_success_at,last_failure_at,last_error,n8n_instance_id,n8n_workflow_id").eq("client_id",id).limit(100),
  s.from("client_reports").select("id,report_type,title,summary,period_start,period_end,metrics,insights,generated_at").eq("client_id",id).eq("visible_to_client",true).order("period_end",{ascending:false}).limit(20),
  s.from("support_tickets").select("id,ticket_number,subject,status,priority,updated_at").eq("client_id",id).order("updated_at",{ascending:false}).limit(50),
  s.from("tasks").select("id,title,status,priority,due_at,client_visible").eq("client_id",id).order("due_at",{ascending:true}).limit(50),
  s.from("client_onboarding").select("identity_complete,portal_complete,commercial_complete,infrastructure_complete,automations_complete,n8n_complete,account_complete,verification_complete,access_sent,completed_at").eq("client_id",id).maybeSingle(),
  s.from("business_events").select("id,event_type,event_value,currency,occurred_at").eq("client_id",id).order("occurred_at",{ascending:false}).limit(50),
 ]);
 if(!client.data)notFound();const c=client.data,p=portal.data;const stageKeys=["identity","portal","commercial","infrastructure","automations","n8n","account","verification"];const complete=stageKeys.filter(k=>Boolean((onboarding.data as any)?.[`${k}_complete`])).length;const ws=workflows.data||[],ss=subs.data||[],ts=tickets.data||[],tk=tasks.data||[],es=events.data||[],ops=ws.length?ws.filter((w:any)=>w.status!=="error"&&w.actual_state===w.desired_state).length/ws.length:1,bill=ss.length?ss.filter((x:any)=>x.status==="active").length/ss.length:1,rel=ts.length?Math.max(0,1-ts.filter((x:any)=>["open","pending_admin"].includes(x.status)).length/ts.length):1,res=es.length?1:.5;
 return <><PageHeader eyebrow="Client operating record" title={c.company_name} description="Full tenant view across business, control and support operations." action={<div className="flex flex-wrap gap-2"><ClientLifecycleActions clientId={c.id} clientStatus={c.status} subscriptionId={ss[0]?.id||null}/><Link href="/admin/clients" className="rounded-xl border border-white/8 px-4 py-2.5 text-sm">Back</Link></div>}/>
 <div className="grid gap-4 xl:grid-cols-3"><section className="vx-surface rounded-2xl p-5 xl:col-span-2"><div className="vx-kicker">Identity</div><div className="mt-4 grid gap-4 sm:grid-cols-2"><Info label="Company" value={c.company_name}/><Info label="Contact" value={c.contact_name||"—"}/><Info label="Email" value={c.email||"—"}/><Info label="Phone" value={c.phone||"—"}/><Info label="Status" value={<StatusBadge value={c.status}/>}/><Info label="Created" value={formatDate(c.created_at)}/></div><div className="mt-5 border-t border-white/6 pt-5"><ClientEditForm client={c}/></div></section><section className="vx-surface rounded-2xl p-5"><div className="vx-kicker">Onboarding readiness</div><div className="mt-2 flex items-end justify-between"><div className="text-3xl font-semibold">{complete}/8</div><div className="text-xs text-slate-500">stages complete</div></div><div className="mt-4 space-y-2">{stageKeys.map(k=><div key={k} className="flex justify-between rounded-xl bg-black/15 px-3 py-2 text-xs"><span className="capitalize text-slate-400">{k}</span><span className={((onboarding.data as any)?.[`${k}_complete`])?"text-emerald-300":"text-slate-600"}>{((onboarding.data as any)?.[`${k}_complete`])?"Complete":"Open"}</span></div>)}</div></section></div>
 <div className="mt-4 grid gap-4 lg:grid-cols-2"><section className="vx-surface rounded-2xl p-5"><div className="flex items-start justify-between gap-3"><div><div className="vx-kicker">Portal</div><div className="mt-1 text-base font-semibold">{p?.portal_title||"—"}</div></div>{p?.slug&&<Link className="text-xs underline" href={`/login/client/${p.slug}`}>Portal login</Link>}</div>{p?<form action={updatePortalConfig} className="mt-4 grid gap-3 sm:grid-cols-2"><input type="hidden" name="clientId" value={p.client_id}/><input name="slug" defaultValue={p.slug} className="vx-field" placeholder="Slug"/><input name="portalTitle" defaultValue={p.portal_title} className="vx-field" placeholder="Portal title"/><input name="primaryColor" defaultValue={p.primary_color||"#111827"} className="vx-field"/><input name="accentColor" defaultValue={p.accent_color||"#2563eb"} className="vx-field"/><div className="sm:col-span-2 text-xs text-slate-500">Enabled modules: {p.enabled_modules.join(", ")}</div><button className="rounded-xl bg-white px-4 py-2.5 text-xs font-bold text-slate-950 sm:col-span-2">Save portal config</button></form>:<EmptyState title="Portal not configured" description="Create portal configuration during onboarding."/>}</section><section className="vx-surface rounded-2xl p-5"><div className="vx-kicker">Health</div><div className="mt-4 grid grid-cols-2 gap-3"><Health label="Operational" value={ops}/><Health label="Billing" value={bill}/><Health label="Relationship" value={rel}/><Health label="Results / usage" value={res}/></div></section></div>
 <div className="mt-4 grid gap-4 lg:grid-cols-2"><section className="vx-surface rounded-2xl p-5"><div className="vx-kicker">Commercial</div>{ss.length?<div className="mt-3 space-y-3">{ss.map((x:any)=><div key={x.id} className="rounded-xl border border-white/6 bg-black/15 p-3"><div className="flex justify-between gap-3"><div><b>{x.service_name}</b><div className="text-xs text-slate-500">{formatMoney(x.monthly_amount,x.currency)} · day {x.billing_day} · {x.auto_renew?"auto-renew":"non-renewing"}</div></div><StatusBadge value={x.status}/></div><BillingActions subscription={x} clientId={c.id}/></div>)}</div>:<EmptyState title="No subscription" description="No commercial record exists yet."/>}</section><section className="vx-surface rounded-2xl p-5"><div className="vx-kicker">Infrastructure</div>{connections.data?.length?<div className="mt-3 space-y-2">{connections.data.map((x:any)=><div key={x.id} className="rounded-xl border border-white/6 bg-black/15 p-3"><div className="flex justify-between gap-3"><span className="text-sm font-semibold">Instance {x.n8n_instance_id}</span><div className="flex gap-2"><StatusBadge value={x.status}/><ConnectionVerifyButton connectionId={x.id}/></div></div><div className="mt-1 text-xs text-slate-500">Verified {formatDateTime(x.last_verified_at)}{x.last_error?` · ${x.last_error}`:""}</div></div>)}</div>:<EmptyState title="No connection" description="This tenant is not connected to a recorded n8n instance."/>}</section></div>
 <section className="mt-4 vx-surface rounded-2xl p-5"><div className="flex items-center justify-between"><div><div className="vx-kicker">Automation health</div><p className="mt-1 text-sm text-slate-500">Business-facing workflow state, not n8n internals.</p></div></div>{ws.length?<div className="mt-4 grid gap-3 md:grid-cols-2">{ws.map((w:any)=><div key={w.id} className="rounded-xl border border-white/6 bg-black/15 p-4"><div className="flex justify-between gap-3"><div><Link href={`/admin/automations/${w.id}`} className="font-semibold hover:underline">{w.business_name||w.workflow_name}</Link><div className="mt-1 text-xs text-slate-500">{w.business_job||"No business job"}</div></div><StatusBadge value={w.actual_state}/></div><div className="mt-2 text-xs text-slate-500">Desired {w.desired_state} · actual {w.actual_state} · success {formatDateTime(w.last_success_at)}</div><div className="mt-3"><AutomationControl workflowId={w.id} actual={w.actual_state} desired={w.desired_state}/></div></div>)}</div>:<EmptyState title="No automations" description="No workflows are assigned to this tenant."/>}</section>
 <div className="mt-4 grid gap-4 lg:grid-cols-3"><section className="vx-surface rounded-2xl p-5 lg:col-span-2"><div className="vx-kicker">Results & reports</div>{reports.data?.length?<div className="mt-3 space-y-3">{reports.data.map((r:any)=><div key={r.id} className="rounded-xl border border-white/6 bg-black/15 p-4"><div className="text-sm font-semibold">{r.title}</div><div className="mt-1 text-xs text-slate-500">{r.report_type} · {r.period_start} → {r.period_end}</div><p className="mt-2 text-sm leading-6 text-slate-400">{r.summary||"No summary supplied."}</p></div>)}</div>:<EmptyState title="No client reports" description="No published client-visible report records exist yet."/>}</section><section className="vx-surface rounded-2xl p-5"><div className="vx-kicker">Recent business events</div>{es.length?<div className="mt-3 space-y-2">{es.slice(0,10).map((e:any)=><div key={e.id} className="rounded-xl bg-black/15 p-3"><div className="text-sm font-semibold">{e.event_type.replaceAll("_"," ")}</div><div className="text-xs text-slate-500">{formatDateTime(e.occurred_at)}{e.event_value!==null?` · ${e.event_value} ${e.currency||""}`:""}</div></div>)}</div>:<EmptyState title="No business events" description="Tracked outcomes appear after trusted event ingestion."/>}</section></div>
 <div className="mt-4 grid gap-4 lg:grid-cols-2"><section className="vx-surface rounded-2xl p-5"><div className="vx-kicker">Support</div>{ts.length?<div className="mt-3 space-y-2">{ts.map((t:any)=><Link key={t.id} href={`/admin/support/${t.id}`} className="flex items-center justify-between rounded-xl border border-white/6 bg-black/15 p-3 hover:border-white/12"><span><b className="text-sm">{t.subject}</b><span className="mt-1 block text-xs text-slate-500">{t.priority} · {formatDateTime(t.updated_at)}</span></span><StatusBadge value={t.status}/></Link>)}</div>:<EmptyState title="No support tickets" description="No support tickets exist for this client."/>}</section><section className="vx-surface rounded-2xl p-5"><div className="vx-kicker">Tasks</div>{tk.length?<div className="mt-3 space-y-2">{tk.map((t:any)=><div key={t.id} className="flex justify-between gap-3 rounded-xl bg-black/15 p-3"><span><b className="text-sm">{t.title}</b><span className="mt-1 block text-xs text-slate-500">Due {formatDateTime(t.due_at)}</span></span><StatusBadge value={t.status}/></div>)}</div>:<EmptyState title="No client tasks" description="No client-linked tasks are currently recorded."/>}</section></div>
 <section className="mt-4 vx-surface rounded-2xl p-5"><div className="vx-kicker">Account access</div><p className="mt-2 text-sm text-slate-500">Client authentication is managed through the real Supabase Auth account. Passwords are never displayed or stored in VectorOps tables.</p></section>
 </>
}
function Info({label,value}:{label:string;value:React.ReactNode}){return <div><div className="text-[10px] uppercase tracking-wide text-slate-500">{label}</div><div className="mt-1 text-sm text-slate-200">{value}</div></div>}
function Health({label,value}:{label:string;value:number}){return <div className="vx-inset rounded-xl p-4"><div className="flex justify-between text-xs"><span className="text-slate-500">{label}</span><b className="text-slate-200">{Math.round(value*100)}%</b></div><div className="mt-2 h-1.5 rounded-full bg-white/5"><div className="h-full rounded-full bg-white/75" style={{width:`${Math.round(value*100)}%`}}/></div></div>}
