import Link from "next/link";
import { ArrowRight, Boxes, Building2, Cpu, Gauge, ShieldCheck, Sparkles } from "lucide-react";
import { getAuthContext } from "@/lib/auth";
import { redirect } from "next/navigation";

export default async function Home() {
  const { profile } = await getAuthContext();
  if (profile?.role === "admin") redirect("/admin");
  if (profile?.role === "client" && profile.client_id) return <div className="vx-shell grid min-h-screen place-items-center p-6"><div className="vx-surface w-full max-w-xl rounded-3xl p-7 text-center"><div className="vx-kicker">Signed in</div><h1 className="mt-2 text-3xl font-semibold">Your VectorOps portal is ready</h1><p className="mx-auto mt-3 max-w-md text-sm leading-6 text-slate-400">Use your tenant URL to continue. Access is bound to your authenticated client relationship.</p><Link href="/" className="mt-6 inline-flex rounded-xl bg-white px-4 py-3 text-sm font-bold text-slate-950">Return</Link></div></div>;
  return <main className="vx-shell vx-grid min-h-screen"><div className="mx-auto grid min-h-screen max-w-7xl items-center gap-10 px-5 py-10 lg:grid-cols-[1.05fr_.95fr]"><section><div className="flex items-center gap-3"><div className="grid size-10 place-items-center rounded-xl bg-white text-sm font-black text-slate-950">V</div><span className="text-sm font-black tracking-[.18em]">VECTOROPS</span></div><div className="mt-16 vx-kicker">Agency operating system</div><h1 className="mt-4 max-w-3xl text-5xl font-semibold tracking-[-.045em] text-white sm:text-6xl">Your agency, under one operating system.</h1><p className="mt-6 max-w-2xl text-base leading-8 text-slate-400">Manage clients, automation health, infrastructure, billing and business results from one command center. The actual Supabase backend remains the source of truth.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/login/admin" className="inline-flex items-center gap-2 rounded-2xl bg-white px-5 py-3.5 text-sm font-bold text-slate-950">Enter admin console <ArrowRight size={17}/></Link><Link href="/login" className="inline-flex items-center gap-2 rounded-2xl border border-white/10 bg-white/[.03] px-5 py-3.5 text-sm font-semibold text-slate-200">Client login</Link></div></section><section className="vx-surface relative overflow-hidden rounded-[2rem] p-5 sm:p-7"><div className="absolute -right-16 -top-20 size-56 rounded-full border border-white/6"/><div className="absolute -right-5 -top-9 size-40 rounded-full border border-white/5"/><div className="vx-kicker">Operating model</div><div className="mt-5 space-y-3"><Layer icon={Building2} label="BUSINESS" note="Clients · Billing · Support · Results"/><Layer icon={Gauge} label="CONTROL" note="Desired state · Sync · Safety"/><Layer icon={Cpu} label="AUTOMATION" note="n8n execution · Verified status"/><Layer icon={Sparkles} label="RESULTS" note="Business events · Reports"/><Layer icon={Boxes} label="CLIENT PORTALS" note="Tenant-specific experience"/></div><div className="mt-6 flex items-center gap-2 rounded-xl border border-white/6 bg-black/20 p-3 text-xs text-slate-500"><ShieldCheck size={15} className="text-emerald-300"/> No fake metrics, no browser n8n secrets, no URL-only tenant trust.</div></section></div></main>;
}
function Layer({ icon:Icon,label,note }:{icon:typeof Building2;label:string;note:string}){ return <div className="vx-inset flex items-center gap-4 rounded-2xl p-4"><div className="grid size-10 place-items-center rounded-xl border border-white/8 bg-white/[.035] text-slate-300"><Icon size={18}/></div><div><div className="text-xs font-bold tracking-[.14em] text-white">{label}</div><div className="mt-1 text-xs text-slate-500">{note}</div></div><ArrowRight size={15} className="ml-auto text-slate-600"/></div> }
