import Link from "next/link";
import { requireClientSlug } from "@/lib/auth";
import { clientOverview } from "@/lib/data";
import { EmptyState } from "@/components/EmptyState";
import { PageHeader } from "@/components/PageHeader";
import { DataTable } from "@/components/DataTable";
import { StatusBadge } from "@/components/StatusBadge";
import { formatDate, formatMoney, formatDateTime } from "@/lib/utils";
import { AutomationControl } from "@/components/AutomationControl";

export default async function ClientSection({params}:{params:Promise<{slug:string;section:string}>}){const {slug,section}=await params;const ctx=await requireClientSlug(slug);const d=await clientOverview(ctx.client.id);const title=section.charAt(0).toUpperCase()+section.slice(1); if(section==="automations")return <><PageHeader eyebrow={ctx.client.company_name} title="Automations" description="Business-facing automation status. Technical n8n internals remain outside the client portal."/>{d.workflows.length===0?<EmptyState title="No automations yet" description="Your VectorOps team has not connected a client-visible automation record yet."/>:<DataTable headers={["Automation","Health","Desired / actual","Last execution","Control"]} rows={d.workflows.map((w:any)=>[w.business_name||w.workflow_name,<StatusBadge value={w.actual_state}/>,<span className="text-xs">{w.desired_state} → {w.actual_state}</span>,formatDateTime(w.last_execution_at),<AutomationControl workflowId={w.id} actual={w.actual_state} desired={w.desired_state}/>])}/>}</>;
if(section==="results")return <><PageHeader eyebrow={ctx.client.company_name} title="Results" description="Tracked outcomes from real business events and client-visible reports."/>{d.events.length===0&&d.reports.length===0?<EmptyState title="No results yet" description="Results appear once trusted business events or published reports exist."/>:<div className="space-y-3">{d.reports.map((r:any)=><section key={r.id} className="vx-surface rounded-2xl p-5"><div className="vx-kicker">{r.report_type}</div><h2 className="mt-1 text-lg font-semibold">{r.title}</h2><p className="mt-2 text-sm leading-6 text-slate-400">{r.summary||"No summary supplied."}</p><div className="mt-4 grid gap-2 sm:grid-cols-3">{Object.entries((r.metrics||{}) as Record<string,unknown>).slice(0,6).map(([k,v])=><div key={k} className="vx-inset rounded-xl p-3"><div className="text-[10px] uppercase tracking-wide text-slate-500">{k.replaceAll("_"," ")}</div><div className="mt-1 text-sm font-semibold text-white">{String(v)}</div></div>)}</div></section>)}{d.events.slice(0,12).map((e:any)=><div key={e.id} className="vx-inset rounded-xl p-3"><div className="text-sm font-semibold">{e.event_type.replaceAll("_"," ")}</div><div className="mt-1 text-xs text-slate-500">{formatDate(e.occurred_at)}{e.event_value!==null?` · ${e.event_value} ${e.currency||""}`:""}</div></div>)}</div>}</>;
if(section==="billing")return <><PageHeader eyebrow={ctx.client.company_name} title="Billing" description="View-only billing records and payment history from the existing billing backend."/><div className="grid gap-3 sm:grid-cols-2"><div className="vx-surface rounded-2xl p-4"><div className="vx-kicker">Current service</div><div className="mt-2 text-lg font-semibold">{d.subscriptions[0]?.service_name||"—"}</div><div className="mt-1 text-sm text-slate-500">{d.subscriptions[0]?`${formatMoney(d.subscriptions[0].monthly_amount,d.subscriptions[0].currency)} / month · ${d.subscriptions[0].auto_renew?"auto-renewing":"non-renewing"}`:"No subscription record"}</div></div><div className="vx-surface rounded-2xl p-4"><div className="vx-kicker">Next billing date</div><div className="mt-2 text-lg font-semibold">{formatDate(d.subscriptions[0]?.current_period_end)}</div><StatusBadge value={d.subscriptions[0]?.status}/></div></div><div className="mt-5">{d.invoices.length===0?<EmptyState title="No invoices" description="Invoice records will appear here when the existing billing process creates them."/>:<DataTable headers={["Invoice","Total","Paid","Status","Due"]} rows={d.invoices.map((i:any)=>[i.invoice_number,formatMoney(i.total_amount,d.subscriptions[0]?.currency||"INR"),formatMoney(i.amount_paid,d.subscriptions[0]?.currency||"INR"),<StatusBadge value={i.status}/>,formatDate(i.due_date)])}/>}</div></>;
if(section==="support")return <><PageHeader eyebrow={ctx.client.company_name} title="Support" description="Open a conversation with the VectorOps agency team."/>{d.tickets.length===0?<EmptyState title="No tickets" description="There are no support tickets for this tenant yet."/>:<DataTable headers={["Ticket","Priority","Status","Updated"]} rows={d.tickets.map((t:any)=>[t.subject,<StatusBadge value={t.priority}/>,<StatusBadge value={t.status}/>,formatDateTime(t.updated_at)])}/>}</>;
if(section==="profile")return <><PageHeader eyebrow={ctx.client.company_name} title="Profile" description="Your tenant identity and portal configuration, without exposing internal credentials or infrastructure secrets."/><div className="grid gap-4 md:grid-cols-2"><section className="vx-surface rounded-2xl p-5"><div className="vx-kicker">Identity</div><div className="mt-4 space-y-3 text-sm"><Row label="Company" value={ctx.client.company_name}/><Row label="Contact" value={ctx.client.contact_name||"—"}/><Row label="Email" value={ctx.client.email||"—"}/><Row label="Phone" value={ctx.client.phone||"—"}/></div></section><section className="vx-surface rounded-2xl p-5"><div className="vx-kicker">Portal</div><div className="mt-4 space-y-3 text-sm"><Row label="Slug" value={ctx.portal.slug}/><Row label="Title" value={ctx.portal.portal_title}/><Row label="Modules" value={ctx.portal.enabled_modules.join(", ")}/></div></section></div></>;
return <><PageHeader eyebrow={ctx.client.company_name} title={title} description="This section is intentionally conservative: it only exposes capabilities backed by the live VectorOps data model."/><EmptyState title="Ready for supported data" description="No records are currently available for this section."/><div className="mt-4"><Link href={`/${slug}`} className="text-sm text-slate-400 underline">Return to overview</Link></div></>}
function Row({label,value}:{label:string;value:string}){return <div className="flex justify-between gap-4 border-b border-white/6 pb-3 last:border-0"><span className="text-slate-500">{label}</span><span className="text-right font-medium text-slate-200">{value}</span></div>}
