"use client";
import { FormEvent, useState } from "react";
import { ArrowRight, Eye, EyeOff, KeyRound, ShieldCheck } from "lucide-react";
import { useRouter } from "next/navigation";

export function LoginForm({ mode, slug }: { mode: "admin" | "client"; slug?: string }) {
  const [password, setPassword] = useState(""); const [show, setShow] = useState(false); const [loading, setLoading] = useState(false); const [error, setError] = useState<string | null>(null); const router = useRouter();
  async function submit(e: FormEvent) { e.preventDefault(); setLoading(true); setError(null); try { const r = await fetch("/api/auth/password-login", { method:"POST", headers:{"content-type":"application/json"}, body: JSON.stringify({ mode, slug, password }) }); const data = await r.json(); if (!r.ok) throw new Error(data.error || "Unable to sign in."); router.replace(mode === "admin" ? "/admin" : `/${slug}`); router.refresh(); } catch (err) { setError(err instanceof Error ? err.message : "Unable to sign in."); } finally { setLoading(false); } }
  return <form onSubmit={submit} className="space-y-5"><div><label className="vx-kicker" htmlFor="password">Password</label><div className="relative mt-2"><KeyRound className="absolute left-4 top-3.5 text-slate-500" size={18}/><input id="password" autoComplete="current-password" required type={show?"text":"password"} value={password} onChange={e=>setPassword(e.target.value)} className="w-full rounded-2xl border border-white/8 bg-black/20 py-3.5 pl-11 pr-12 text-sm outline-none focus:border-white/20" placeholder="Enter your password"/><button type="button" onClick={()=>setShow(v=>!v)} className="absolute right-3 top-2.5 rounded-xl p-2 text-slate-400 hover:bg-white/5" aria-label={show?"Hide password":"Show password"}>{show?<EyeOff size={18}/>:<Eye size={18}/>}</button></div></div>{error && <div role="alert" className="rounded-xl border border-red-400/15 bg-red-400/5 px-3 py-2.5 text-sm text-red-200">{error}</div>}<button disabled={loading} className="group flex w-full items-center justify-between rounded-2xl border border-white/10 bg-white px-4 py-3.5 text-sm font-bold text-slate-950 disabled:opacity-60"><span>{loading ? "VERIFYING…" : mode === "admin" ? "ENTER ADMIN CONSOLE" : "ENTER PORTAL"}</span><ArrowRight size={17}/></button><div className="flex items-center gap-2 text-xs text-slate-500"><ShieldCheck size={14}/> Identity is verified against Supabase Auth and the real tenant relationship.</div></form>;
}
