"use client";
import { useMemo, useState } from "react";
import { createClientOnboarding } from "@/lib/actions";

const steps=[["Identity","Company, contact and tenant notes."],["Portal","Slug, title and branding."],["Commercial","Service, price, currency and billing day."],["Infrastructure","Choose shared or dedicated from recorded instances."],["Automation package","Select an active package without claiming deployment."],["n8n setup","Attach the explicit existing instance relationship."],["Account access","Provision the real Supabase Auth account."],["Verification","Review persisted prerequisites."],["Ready","Create the tenant." ]] as const;

export function OnboardingWizard({instances,templates}:{instances:any[];templates:any[]}){
 const [step,setStep]=useState(0); const [busy,setBusy]=useState(false); const [error,setError]=useState<string|null>(null); const [form,setForm]=useState<Record<string,string>>({currency:"INR",billing_day:"1",primary_color:"#111827",accent_color:"#2563eb"});
 const set=(k:string,v:string)=>setForm(x=>({...x,[k]:v})); const total=steps.length; const isLast=step===total-1;
 const selectedInstance=instances.find(x=>x.id===form.n8n_instance_id);
 const canNext=useMemo(()=>step===0?Boolean(form.company_name&&form.slug):step===2?Boolean(form.service_name&&form.monthly_amount!==undefined):true,[step,form]);
 async function submit(){setBusy(true);setError(null);const fd=new FormData();Object.entries(form).forEach(([k,v])=>fd.set(k,v));try{await createClientOnboarding(fd);window.location.href="/admin/clients"}catch(e){setError(e instanceof Error?e.message:"Client onboarding failed.");setBusy(false)}}
 return <div className="grid gap-5 lg:grid-cols-[240px_1fr]"><aside className="vx-surface h-fit rounded-2xl p-4 lg:sticky lg:top-24"><div className="vx-kicker">Onboarding</div><div className="mt-4 space-y-1">{steps.map(([name,desc],i)=><button type="button" key={name} onClick={()=>i<=step&&setStep(i)} className={`w-full rounded-xl px-3 py-3 text-left ${i===step?"bg-white text-slate-950":"text-slate-400 hover:bg-white/[.04]"}`}><div className="flex items-start gap-3"><span className={`grid size-6 shrink-0 place-items-center rounded-full text-[10px] font-bold ${i<step?"bg-emerald-300 text-slate-950":i===step?"bg-slate-900 text-white":"bg-white/5 text-slate-500"}`}>{i<step?"✓":i+1}</span><span><span className="block text-xs font-semibold">{name}</span><span className="mt-1 block text-[10px] leading-4 text-slate-600">{desc}</span></span></div></button>)}</div></aside><section className="vx-surface rounded-2xl p-5 sm:p-7"><div className="flex items-center justify-between gap-3"><div><div className="vx-kicker">Step {step+1} of {total}</div><h2 className="mt-1 text-2xl font-semibold text-white">{steps[step][0]}</h2><p className="mt-1 text-sm text-slate-500">{steps[step][1]}</p></div><div className="text-xs text-slate-500">{Math.round(((step+1)/total)*100)}%</div></div><div className="mt-7">
 {step===0&&<div className="grid gap-4 sm:grid-cols-2"><Field label="Company" value={form.company_name||""} onChange={v=>set("company_name",v)} required/><Field label="Contact" value={form.contact_name||""} onChange={v=>set("contact_name",v)}/><Field label="Email" type="email" value={form.email||""} onChange={v=>set("email",v)}/><Field label="Phone" value={form.phone||""} onChange={v=>set("phone",v)}/><Field label="Portal slug" placeholder="acme-dental" value={form.slug||""} onChange={v=>set("slug",v.toLowerCase())} required/><Field label="Notes" value={form.notes||""} onChange={v=>set("notes",v)} textarea/></div>}
 {step===1&&<div className="grid gap-4 sm:grid-cols-2"><Field label="Portal title" value={form.portal_title||"Client Portal"} onChange={v=>set("portal_title",v)}/><Field label="Logo URL" value={form.logo_url||""} onChange={v=>set("logo_url",v)}/><Field label="Favicon URL" value={form.favicon_url||""} onChange={v=>set("favicon_url",v)}/><Field label="Primary color" value={form.primary_color||"#111827"} onChange={v=>set("primary_color",v)}/><Field label="Accent color" value={form.accent_color||"#2563eb"} onChange={v=>set("accent_color",v)}/><div className="sm:col-span-2 vx-inset rounded-xl p-4 text-xs leading-5 text-slate-500">Module, KPI, dashboard and terminology data remain tenant-specific in the existing portal configuration model.</div></div>}
 {step===2&&<div className="grid gap-4 sm:grid-cols-2"><Field label="Service" value={form.service_name||""} onChange={v=>set("service_name",v)} required/><Field label="Monthly amount" type="number" value={form.monthly_amount||"0"} onChange={v=>set("monthly_amount",v)}/><Field label="Currency" value={form.currency||"INR"} onChange={v=>set("currency",v.toUpperCase())}/><Field label="Billing day" type="number" value={form.billing_day||"1"} onChange={v=>set("billing_day",v)}/></div>}
 {step===3&&<div className="space-y-4"><div className="grid gap-3 sm:grid-cols-2"><button type="button" onClick={()=>set("infrastructure_mode","shared")} className={`rounded-2xl border p-5 text-left ${form.infrastructure_mode!=="dedicated"?"border-white bg-white/[.04]":"border-white/8"}`}><div className="text-sm font-semibold">Shared</div><p className="mt-1 text-xs text-slate-500">Use an existing shared instance explicitly.</p></button><button type="button" onClick={()=>set("infrastructure_mode","dedicated")} className={`rounded-2xl border p-5 text-left ${form.infrastructure_mode==="dedicated"?"border-white bg-white/[.04]":"border-white/8"}`}><div className="text-sm font-semibold">Dedicated</div><p className="mt-1 text-xs text-slate-500">Use a dedicated instance when the backend already records one.</p></button></div>{selectedInstance&&<div className="vx-inset rounded-xl p-4 text-sm"><div className="vx-kicker">Selected instance</div><div className="mt-1 font-semibold">{selectedInstance.instance_name}</div></div>}</div>}
 {step===4&&<div className="grid gap-3 md:grid-cols-2">{templates.map(t=><button type="button" key={t.id} onClick={()=>set("template_id",t.id)} className={`rounded-2xl border p-4 text-left ${form.template_id===t.id?"border-white bg-white/[.04]":"border-white/8"}`}><div className="text-sm font-semibold">{t.name}</div><div className="mt-1 text-xs text-slate-500">{t.category||"Automation"}</div><p className="mt-2 text-xs leading-5 text-slate-500">{t.description||"No description supplied."}</p></button>)}{!templates.length&&<div className="vx-inset rounded-xl p-4 text-sm text-slate-500">No active templates are currently recorded.</div>}</div>}
 {step===5&&<div className="space-y-4"><label><span className="text-xs font-semibold text-slate-300">Existing n8n instance</span><select value={form.n8n_instance_id||""} onChange={e=>set("n8n_instance_id",e.target.value)} className="mt-2 w-full rounded-xl border border-white/8 bg-black/20 px-3 py-3 text-sm"><option value="">Not connected yet</option>{instances.map(i=><option key={i.id} value={i.id}>{i.instance_name} · {i.hosting_type} · {i.status}</option>)}</select></label><div className="rounded-xl border border-amber-400/10 bg-amber-400/[.03] p-4 text-xs leading-5 text-amber-100/75">No raw n8n credential is collected. A connection remains pending until the real verification/control process confirms it.</div></div>}
 {step===6&&<div className="grid gap-4 sm:grid-cols-2"><Field label="Client account email" type="email" value={form.email||""} onChange={v=>set("email",v)} required/><Field label="Initial password" type="password" autoComplete="new-password" value={form.client_password||""} onChange={v=>set("client_password",v)}/><div className="sm:col-span-2 vx-inset rounded-xl p-4 text-xs leading-5 text-slate-500">The password is consumed by the trusted server action and sent only to Supabase Auth. It is never stored in VectorOps data.</div></div>}
 {step===7&&<div className="grid gap-4 sm:grid-cols-2">{[["Identity","company_name"],["Portal","portal_title"],["Commercial","service_name"],["Infrastructure","n8n_instance_id"],["Automation package","template_id"],["Account access","client_password"]].map(([label,key])=><div key={key} className="vx-inset rounded-xl p-4"><div className="vx-kicker">{label}</div><div className="mt-1 text-sm font-medium text-slate-200">{key==="client_password"?(form[key]?"Configured":"Not configured"):form[key]||"Not configured"}</div></div>)}<div className="sm:col-span-2 text-xs leading-5 text-slate-500">Final verification is based on actual persisted state. A saved n8n instance is not displayed as connected until verification.</div></div>}
 {step===8&&<div className="space-y-4"><div className="vx-inset rounded-2xl p-5"><div className="text-sm font-semibold text-white">Ready to create tenant</div><p className="mt-2 text-sm leading-6 text-slate-400">This creates the real client and supported related records. Unsupported future services remain unconfigured.</p></div></div>}
 </div>{error&&<div role="alert" className="mt-5 rounded-xl border border-red-400/10 bg-red-400/[.04] p-3 text-sm text-red-200">{error}</div>}<div className="mt-7 flex items-center justify-between gap-3 border-t border-white/6 pt-5"><button type="button" disabled={step===0||busy} onClick={()=>setStep(Math.max(0,step-1))} className="rounded-xl border border-white/8 px-4 py-2.5 text-sm text-slate-300">Back</button><div className="flex gap-2"><button type="button" onClick={()=>window.location.href="/admin/clients"} className="rounded-xl border border-white/8 px-4 py-2.5 text-sm text-slate-400">Cancel</button>{isLast?<button type="button" disabled={busy||!form.company_name||!form.slug} onClick={submit} className="rounded-xl bg-white px-5 py-2.5 text-sm font-bold text-slate-950">{busy?"Creating…":"Create client"}</button>:<button type="button" disabled={!canNext} onClick={()=>setStep(Math.min(total-1,step+1))} className="rounded-xl bg-white px-5 py-2.5 text-sm font-bold text-slate-950">Continue</button>}</div></div></section></div>
}
function Field({label,value,onChange,type="text",placeholder,required,textarea,autoComplete}:{label:string;value:string;onChange:(v:string)=>void;type?:string;placeholder?:string;required?:boolean;textarea?:boolean;autoComplete?:string}){return <label><span className="text-xs font-semibold text-slate-300">{label}{required?" *":""}</span>{textarea?<textarea value={value} onChange={e=>onChange(e.target.value)} rows={4} placeholder={placeholder} className="mt-2 w-full rounded-xl border border-white/8 bg-black/20 px-3 py-3 text-sm text-slate-200 outline-none"/>:<input value={value} onChange={e=>onChange(e.target.value)} type={type} placeholder={placeholder} required={required} autoComplete={autoComplete} className="mt-2 w-full rounded-xl border border-white/8 bg-black/20 px-3 py-3 text-sm text-slate-200 outline-none"/>}</label>}
