"use client";
import { useState } from "react";
import { createSupportTicket } from "@/lib/actions";

export function SupportTicketForm() {
  const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null);
  async function submit(formData: FormData) { setBusy(true); setError(null); try { await createSupportTicket(formData); window.location.reload(); } catch (e) { setError(e instanceof Error ? e.message : "Ticket could not be created."); } finally { setBusy(false); } }
  return <form action={submit} className="vx-surface rounded-2xl p-5"><div className="vx-kicker">Create ticket</div><div className="mt-4 grid gap-3 sm:grid-cols-2"><input name="subject" required maxLength={160} placeholder="What do you need help with?" className="rounded-xl border border-white/8 bg-black/20 px-3 py-3 text-sm sm:col-span-2" /><select name="category" className="rounded-xl border border-white/8 bg-black/20 px-3 py-3 text-sm"><option value="">Category</option><option value="automation">Automation</option><option value="billing">Billing</option><option value="support">Support</option><option value="account">Account</option><option value="other">Other</option></select><select name="priority" defaultValue="normal" className="rounded-xl border border-white/8 bg-black/20 px-3 py-3 text-sm"><option value="low">Low</option><option value="normal">Normal</option><option value="high">High</option><option value="urgent">Urgent</option></select><textarea name="message" required maxLength={10000} rows={5} placeholder="Describe the issue and what you need next." className="rounded-xl border border-white/8 bg-black/20 px-3 py-3 text-sm sm:col-span-2" /><div className="flex items-center justify-between gap-3 sm:col-span-2"><p className="text-xs text-slate-500">Use only business context. Never include API keys or passwords.</p><button disabled={busy} className="rounded-xl bg-white px-4 py-3 text-sm font-bold text-slate-950">{busy?"Creating…":"Create ticket"}</button></div>{error&&<div role="alert" className="sm:col-span-2 text-xs text-red-300">{error}</div>}</div></form>;
}
