/** Synced from the connected VectorOps Supabase public schema. */
export type Json = string | number | boolean | null | { [key:string]: Json|undefined } | Json[];
type Table<R,I=Partial<R>,U=Partial<R>>={Row:R;Insert:I;Update:U;Relationships:never[]};
type DatabaseEnums={adjustment_type:"free_days"|"discount"|"credit"|"goodwill_extension"|"pause"|"renewal_date_change";app_role:"admin"|"client";automation_state:"unknown"|"running"|"paused"|"disabled";calendar_event_status:"scheduled"|"completed"|"cancelled";calendar_event_type:"meeting"|"call"|"onboarding"|"renewal"|"internal"|"other";client_status:"pending"|"active"|"paused"|"churned"|"archived";connection_status:"pending"|"connected"|"error"|"disabled";control_sync_status:"idle"|"pending"|"syncing"|"success"|"error";discovered_workflow_status:"unmapped"|"mapped"|"ignored";instance_hosting_type:"shared"|"dedicated";instance_status:"provisioning"|"active"|"maintenance"|"offline"|"retired";invoice_status:"draft"|"due"|"partially_paid"|"paid"|"void"|"overdue";invoice_type:"initial"|"renewal"|"adjustment";payment_status:"received"|"reversed"|"refunded";subscription_status:"pending"|"active"|"paused"|"cancelled"|"expired";sync_status:"idle"|"pending"|"syncing"|"success"|"error"|"stale";task_priority:"low"|"medium"|"high"|"urgent";task_status:"todo"|"in_progress"|"blocked"|"completed"|"cancelled";ticket_priority:"low"|"normal"|"high"|"urgent";ticket_status:"open"|"pending_client"|"pending_admin"|"resolved"|"closed";workflow_status:"draft"|"active"|"paused"|"disabled"|"error"|"archived"};
export type Database={public:{Tables:{[key:string]:Table<Record<string,any>>}&Record<string,Table<Record<string,any>>>;Views:Record<string,never>;Functions:Record<string,{Args:Record<string,unknown>;Returns:any}>;Enums:DatabaseEnums;CompositeTypes:Record<string,never>}};
export type Tables<T extends keyof Database["public"]["Tables"]>=Database["public"]["Tables"][T]["Row"];
export type TablesInsert<T extends keyof Database["public"]["Tables"]>=Database["public"]["Tables"][T]["Insert"];
export type TablesUpdate<T extends keyof Database["public"]["Tables"]>=Database["public"]["Tables"][T]["Update"];
export type Enums<T extends keyof DatabaseEnums>=DatabaseEnums[T];
