import { EmptyState } from "@/components/EmptyState";
import { Metric } from "@/components/Metric";
import { PageHeader } from "@/components/PageHeader";
import { StatusBadge } from "@/components/StatusBadge";
import { DataTable } from "@/components/DataTable";
import { requireClientSlug } from "@/lib/auth";
import { clientOverview } from "@/lib/data";
import { formatDate } from "@/lib/utils";

export default async function ClientOverview({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const ctx=await requireClientSlug(slug);const d=await clientOverview(ctx.client.id);const visibleEvents=d.events.slice(0,100);const visibleMetrics=visibleEvents.reduce((acc:any,e:any)=>{const k=e.event_type;acc[k]=(acc[k]||0)+1;return acc},{});return <><PageHeader eyebrow={ctx.client.company_name} title="Business overview" description="A client-specific operating view built from your actual automation and business-event records."/><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{["lead_captured","appointment_booked","review_received","message_sent"].map(k=><Metric key={k} label={k.replaceAll("_"," ")} value={visibleMetrics[k] ? String(visibleMetrics[k]) : "—"} detail={visibleMetrics[k] ? "Tracked business events" : "No recorded events"}/>)}</div><div className="mt-5 grid gap-4 lg:grid-cols-[1.1fr_.9fr]"><section className="vx-surface rounded-2xl p-4"><div className="mb-4 text-sm font-semibold">Automation health</div>{d.workflows.length===0?<EmptyState title="No client-visible automations" description="Once an automation is configured and marked client-visible, its verified state will appear here."/>:<DataTable headers={["Automation","State","Last success"]} rows={d.workflows.map((w:any)=>[w.business_name||w.workflow_name,<StatusBadge value={w.actual_state}/>,formatDate(w.last_success_at)])}/>}</section><section className="vx-surface rounded-2xl p-4"><div className="mb-4 text-sm font-semibold">Latest results</div>{d.events.length===0?<EmptyState title="No results yet" description="Business outcomes will appear after the trusted automation telemetry records them."/>:<div className="space-y-2">{d.events.slice(0,8).map((e:any)=><div key={e.id} className="vx-inset rounded-xl p-3"><div className="text-sm font-semibold text-white">{e.event_type.replaceAll("_"," ")}</div><div className="mt-1 text-xs text-slate-500">{formatDate(e.occurred_at)}{e.event_value!==null?` · ${e.event_value} ${e.currency||""}`:""}</div></div>)}</div>}</section></div></>}
