import { NextRequest, NextResponse } from "next/server";
import { createServerClient } from "@supabase/ssr";
import { createAdminClient } from "@/lib/supabase/admin";

const genericFailure="We couldn't verify your access right now. Please try again.";
const clientSlug=/^[a-z0-9][a-z0-9-]{1,62}[a-z0-9]$/;

export async function POST(request:NextRequest){try{const body=await request.json() as {password?:string;mode?:"admin"|"client";slug?:string};if(!body.password||!body.mode)return NextResponse.json({error:"Incorrect password."},{status:400});const admin=createAdminClient();let email:string|null=null;let targetUserId:string|null=null;
 if(body.mode==="admin"){email=process.env.ADMIN_AUTH_EMAIL||null;if(!email)return NextResponse.json({error:genericFailure},{status:503});const{data:identity,error:identityError}=await admin.auth.admin.listUsers({page:1,perPage:1000});if(identityError)return NextResponse.json({error:genericFailure},{status:503});const target=identity.users.find(u=>u.email?.toLowerCase()===email!.toLowerCase());const{data:profile}=target?await admin.from("profiles").select("user_id,role,client_id").eq("user_id",target.id).maybeSingle():{data:null};if(!target||!profile||profile.role!=="admin"||profile.client_id!==null)return NextResponse.json({error:"This account does not have administrator access."},{status:403});targetUserId=target.id;email=target.email||email;
 }else{if(!body.slug||!clientSlug.test(body.slug))return NextResponse.json({error:"You don't have access to this portal."},{status:403});const{data:portal}=await admin.from("client_portal_config").select("client_id,slug").eq("slug",body.slug).maybeSingle();if(!portal)return NextResponse.json({error:"You don't have access to this portal."},{status:403});const{data:client}=await admin.from("clients").select("id,status").eq("id",portal.client_id).maybeSingle();const{data:profile}=await admin.from("profiles").select("user_id,role,client_id").eq("client_id",portal.client_id).eq("role","client").maybeSingle();if(!client||!profile||profile.client_id!==portal.client_id||!["active","pending"].includes(client.status))return NextResponse.json({error:"This account is currently unavailable."},{status:403});const{data:authUser,error:authLookupError}=await admin.auth.admin.getUserById(profile.user_id);if(authLookupError||!authUser.user?.email)return NextResponse.json({error:genericFailure},{status:503});targetUserId=profile.user_id;email=authUser.user.email;
 }
 const url=process.env.NEXT_PUBLIC_SUPABASE_URL,key=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY;if(!url||!key||!email||!targetUserId)return NextResponse.json({error:genericFailure},{status:503});const response=NextResponse.json({ok:true},{status:200});const supabase=createServerClient(url,key,{cookies:{getAll:()=>request.cookies.getAll(),setAll:items=>items.forEach(({name,value,options})=>response.cookies.set(name,value,options))}});const{error}=await supabase.auth.signInWithPassword({email,password:body.password});if(error)return NextResponse.json({error:"Incorrect password."},{status:401});const{data:{user}}=await supabase.auth.getUser();if(!user||user.id!==targetUserId){return NextResponse.json({error:genericFailure},{status:403})}const{data:verifiedProfile}=await supabase.from("profiles").select("user_id,role,client_id").eq("user_id",user.id).maybeSingle();if(body.mode==="admin"?!verifiedProfile||verifiedProfile.role!=="admin"||verifiedProfile.client_id!==null:!verifiedProfile||verifiedProfile.role!=="client"||verifiedProfile.client_id===null){return NextResponse.json({error:genericFailure},{status:403})}return response;}catch{return NextResponse.json({error:genericFailure},{status:500})}}
