import Link from "next/link";
import { PageHeader } from "@/components/PageHeader";
import { Metric } from "@/components/Metric";
import { StatusBadge } from "@/components/StatusBadge";
import { EmptyState } from "@/components/EmptyState";
import { DataTable } from "@/components/DataTable";
import { adminOverview } from "@/lib/data";
import { formatDate, formatDateTime, formatMoney, titleCase } from "@/lib/utils";
import { AutomationControl } from "@/components/AutomationControl";

export default async function AdminSection({params}:{params:Promise<{section:string}>}) { const {section}=await params; const d=await adminOverview(); const title=titleCase(section); const common=<PageHeader eyebrow="Admin Command Center" title={title} description={sectionDescription(section)} action={section==="clients"?<Link href="/admin/clients/new" className="rounded-xl bg-white px-4 py-2.5 text-sm font-bold text-slate-950">Add client</Link>:undefined}/>;
  if(section==="overview") return <>{common}<div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Active clients" value={String(d.activeClients)} /><Metric label="MRR" value={formatMoney(d.mrr)} detail="Active subscriptions only"/><Metric label="Outstanding" value={formatMoney(d.outstanding)}/><Metric label="Overdue" value={formatMoney(d.overdue)}/></div><div className="mt-3 grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><Metric label="Open tickets" value={String(d.openTickets)}/><Metric label="Workflow attention" value={String(d.workflowFailures)}/><Metric label="Infrastructure issues" value={String(d.infraIssues)}/><Metric label="Collected revenue" value={formatMoney(d.invoices.reduce((s:number,x:any)=>s+Number(x.amount_paid||0),0))}/><Metric label="Subscriptions" value={String(d.subscriptions.length)}/></div><div className="mt-6 grid gap-4 lg:grid-cols-2"><Panel title="Attention required"><div className="space-y-2">{d.invoices.filter((x:any)=>x.status==="overdue").slice(0,5).map((x:any)=><Attention key={x.id} title={`Overdue invoice ${x.invoice_number}`} detail={`${formatMoney(Number(x.total_amount)-Number(x.amount_paid))} outstanding`} severity="High"/>)}{d.workflowFailures>0 && <Attention title={`${d.workflowFailures} automation items need review`} detail="Desired and actual state are not aligned, or a workflow is in error." severity="Medium"/>}{d.infraIssues>0 && <Attention title={`${d.infraIssues} infrastructure items need attention`} detail="Only recorded backend states are shown." severity="Medium"/>}{d.openTickets===0&&d.workflowFailures===0&&d.infraIssues===0&&d.overdue===0&&<EmptyState title="No attention items" description="There are no recorded billing, automation, infrastructure or support issues requiring action."/>}</div></Panel><Panel title="Client health"><DataTable headers={["Client","Status","MRR","Tickets"]} rows={d.clients.slice(0,10).map((c:any)=>[c.company_name,<StatusBadge value={c.status}/>,formatMoney(d.subscriptions.filter((s:any)=>s.client_id===c.id&&s.status==="active").reduce((s:number,x:any)=>s+Number(x.monthly_amount||0),0)),String(d.tickets.filter((t:any)=>t.client_id===c.id).length)])}/></Panel></div></>;
  if(section==="clients") return <>{common}{d.clients.length===0?<EmptyState title="No clients yet" description="Create the first client to establish a tenant, portal configuration and onboarding record."/>:<DataTable headers={["Client","Status","Subscription","Open tickets","Created"]} rows={d.clients.map((c:any)=>[<Link key={c.id} className="font-semibold text-white hover:underline" href={`/admin/clients/${c.id}`}>{c.company_name}</Link>,<StatusBadge value={c.status}/>,formatMoney(d.subscriptions.filter((s:any)=>s.client_id===c.id&&s.status==="active").reduce((s:number,x:any)=>s+Number(x.monthly_amount||0),0)),String(d.tickets.filter((t:any)=>t.client_id===c.id).length),formatDate(c.created_at)])}/>}</>;
  if(section==="automations") return <>{common}{d.workflows.length===0?<EmptyState title="No automation records" description="Automation records will appear here once the existing control/discovery process provisions them."/>:<DataTable headers={["Automation","Client","Status","Desired / actual","Control"]} rows={d.workflows.map((w:any)=>[<Link key={w.id} href={`/admin/automations/${w.id}`} className="font-semibold text-white hover:underline">{w.business_name||w.workflow_name}</Link>,d.clients.find((c:any)=>c.id===w.client_id)?.company_name||"—",<StatusBadge value={w.status}/>,<span className="text-xs">{w.desired_state} → {w.actual_state}</span>,<AutomationControl workflowId={w.id} actual={w.actual_state} desired={w.desired_state}/>])}/>}</>;
  if(section==="money") return <>{common}<div className="grid gap-3 sm:grid-cols-3"><Metric label="Collected" value={formatMoney(d.invoices.reduce((s:number,x:any)=>s+Number(x.amount_paid||0),0))}/><Metric label="Outstanding" value={formatMoney(d.outstanding)}/><Metric label="Overdue" value={formatMoney(d.overdue)}/></div><div className="mt-5">{d.invoices.length===0?<EmptyState title="No invoices" description="Invoices will appear here from the existing billing backend."/>:<DataTable headers={["Invoice","Client","Total","Paid","Status","Due"]} rows={d.invoices.map((x:any)=>[x.invoice_number,d.clients.find((c:any)=>c.id===x.client_id)?.company_name||"—",formatMoney(x.total_amount),formatMoney(x.amount_paid),<StatusBadge value={x.status}/>,formatDate(x.due_date)])}/>}</div></>;
  if(section==="support") return <>{common}{d.tickets.length===0?<EmptyState title="No open tickets" description="Client support tickets will appear here. Internal notes are kept out of client-facing data."/>:<DataTable headers={["Ticket","Client","Priority","Status","Created"]} rows={d.tickets.map((t:any)=>[t.subject,d.clients.find((c:any)=>c.id===t.client_id)?.company_name||"—",<StatusBadge value={t.priority}/>,<StatusBadge value={t.status}/>,formatDateTime(t.created_at)])}/>}</>;
  if(section==="infrastructure") return <>{common}{d.infrastructure.length===0?<EmptyState title="No n8n instances" description="Provisioning is intentionally separate from claiming a successful connection. Records here reflect the database only."/>:<DataTable headers={["Instance","Status","Sync","Last sync","Last error"]} rows={d.infrastructure.map((i:any)=>[i.instance_name,<StatusBadge value={i.status}/>,<StatusBadge value={i.last_sync_status}/>,formatDateTime(i.last_sync_at),i.last_sync_error||"—"])}/>}</>;
  if(section==="tasks") return <><PageHeader eyebrow="Admin Command Center" title="Tasks" description="Operational work across onboarding, clients and internal follow-up."/><TaskSection/></>;
  if(section==="calendar") return <><PageHeader eyebrow="Admin Command Center" title="Calendar" description="Meetings, renewals, calls, onboarding and operational events from the existing calendar records."/><CalendarSection/></>;
  if(section==="activity"||section==="audit") return <><PageHeader eyebrow="Admin Command Center" title={title} description="This screen is intentionally data-driven. No activity or audit records are fabricated."/><EmptyState title={`No ${section} records available`} description="Once the backend has recorded events for this area, VectorOps will display them here without synthesizing missing history."/></>;
  return <>{common}<EmptyState title={`${title} is ready for backend records`} description="The route is wired into the Next.js shell and authorization layer. This area only renders states supported by the live data model; it does not invent unsupported backend operations."/></>;
}
function sectionDescription(s:string){const m:Record<string,string>={overview:"Operational view across clients, money, automation and infrastructure.",clients:"Manage agency tenants and their lifecycle.",automations:"Monitor business automations and desired versus actual state.",money:"Subscriptions, invoices, payments and billing visibility.",calendar:"Operational calendar and renewal rhythm.",tasks:"Agency work queue and follow-through.",support:"Client tickets and agency response workflow.",infrastructure:"Servers, n8n instances, connections and health signals.",activity:"Operational timeline from recorded system events.",audit:"Mutation history with actor, target, before and after."};return m[s]||"Operational workspace."}
function Panel({title,children}:{title:string;children:React.ReactNode}){return <section className="vx-surface rounded-2xl p-4"><div className="mb-4 text-sm font-semibold text-slate-200">{title}</div>{children}</section>}
function Attention({title,detail,severity}:{title:string;detail:string;severity:string}){return <div className="rounded-xl border border-white/7 bg-black/15 p-3"><div className="flex items-center gap-2"><span className="text-sm font-semibold text-white">{title}</span><StatusBadge value={severity}/></div><p className="mt-1 text-xs leading-5 text-slate-500">{detail}</p></div>}
async function TaskSection(){const s=await (await import("@/lib/supabase/server")).createClient();const {data}=await s.from("tasks").select("id,title,status,priority,due_at,client_id,client_visible").order("due_at",{ascending:true}).limit(100);if(!data?.length)return <EmptyState title="No tasks" description="No task records are currently available."/>;return <DataTable headers={["Task","Status","Priority","Due"]} rows={data.map((t:any)=>[t.title,<StatusBadge value={t.status}/>,<StatusBadge value={t.priority}/>,formatDateTime(t.due_at)])}/>}
async function CalendarSection(){const s=await (await import("@/lib/supabase/server")).createClient();const {data}=await s.from("calendar_events").select("id,title,event_type,status,starts_at,ends_at,client_id").order("starts_at",{ascending:true}).limit(100);if(!data?.length)return <EmptyState title="No scheduled events" description="No calendar records are currently available."/>;return <DataTable headers={["Event","Type","Status","Starts"]} rows={data.map((e:any)=>[e.title,<StatusBadge value={e.event_type}/>,<StatusBadge value={e.status}/>,formatDateTime(e.starts_at)])}/>} 
